name: test
description: A test app for Bake!
version: 1.0.0
publish_to: none
homepage: https://github.com/iamtheblackunicorn/Bake
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  bake:
    git: git://github.com/iamtheblackunicorn/Bake.git
